dist: xenial
language: python
cache: pip

python:
  - "3.9"
  - "3.8"

env:
  - DJANGO="https://github.com/django/django/archive/main.tar.gz"
  - DJANGO="Django==3.1.*"

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/main.tar.gz"

  include:
    - python: "3.6"
      env: DJANGO="Django==3.1.*"
    - python: "3.7"
      env: DJANGO="Django==3.1.*"
    - python: "3.8"
      env: DJANGO="Django==3.1.*"
    - python: "3.9"
      env: DJANGO="Django==3.1.*"

    - python: "3.6"
      env: DJANGO="Django==3.0.*"
    - python: "3.7"
      env: DJANGO="Django==3.0.*"
    - python: "3.8"
      env: DJANGO="Django==3.0.*"
    - python: "3.9"
      env: DJANGO="Django==3.0.*"

    - python: "3.5"
      env: DJANGO="Django==2.2.*"
    - python: "3.6"
      env: DJANGO="Django==2.2.*"
    - python: "3.7"
      env: DJANGO="Django==2.2.*"
    - python: "3.8"
      env: DJANGO="Django==2.2.*"
    - python: "3.9"
      env: DJANGO="Django==2.2.*"

    - python: "3.5"
      env: DJANGO="Django==2.1.*"
    - python: "3.6"
      env: DJANGO="Django==2.1.*"
    - python: "3.7"
      env: DJANGO="Django==2.1.*"

    - python: "3.4"
      env: DJANGO="Django==2.0.*"
    - python: "3.5"
      env: DJANGO="Django==2.0.*"
    - python: "3.6"
      env: DJANGO="Django==2.0.*"
    - python: "3.7"
      env: DJANGO="Django==2.0.*"

install:
  - pip install -q $DJANGO
  - pip install -r requirements-dev.txt
  - pip install isort
  - pip install coveralls

script:
   - pytest
   - isort . --check-only

after_success:
  - coveralls
